using OfficeOpenXml.FormulaParsing.Excel.Functions.Math;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Interface.Models.UserRole
{
    public class jsTreeRole
    {
     
        public string text { get; set; }//Role Title
        public string id { get; set; }//RoleName (if start with -, it is category only,it's not role)
        public string icon { get; set; }
        public State state { get; set; }
        public List<jsTreeRole> children { get; set; }

        public jsTreeRole()
        {
            state = new State();
            icon = "glyphicon glyphicon-flash";
        }
    }
    

    public class State
    {
        public bool opened { get; set; }
        public bool disabled { get; set; }
        public bool selected { get; set; }
        public State()
        {
            selected = false;
            disabled = false;
            opened = false;
        }
    }


    public class jsTreeRoleModel
    {
        public List<jsTreeRole> Roles { get; set; } 
    }

    /*
    
    {
            : "string" // will be autogenerated if omitted
          : "string" // node text
          : "string" // string for custom
  state       : {
    opened    : boolean  // is the node open
    disabled  : boolean  // is the node disabled
    selected  : boolean  // is the node selected
  },
  children    : []  // array of strings or objects
  li_attr     : {}  // attributes for the generated LI node
  a_attr      : {}  // attributes for the generated A node
}
    
    */
}